http:
    port: 26670

postgres:
    pool_max: 80

rabbitmq:
    wait_time: 5
    attempts: 10

sinopac:
    pool_max: 20

history:
    # unit: day
    history_close_period: 65
    history_tick_period: 12
    history_kbar_period: 65

simulation: true

trade_switch:
    allow_trade: true
    # unit: second
    hold_time_from_open: 45

    # unit: minute
    total_open_time: 270
    trade_in_end_time: 90

    # unit: seccond
    trade_in_wait_time: 45
    trade_out_wait_time: 60
    cancel_wait_time: 30

future_trade_switch:
    allow_trade: true
    quantity: 1
    # unit: seccond
    trade_in_wait_time: 10
    trade_out_wait_time: 20
    cancel_wait_time: 30
    trade_time_range:
        # HH:MM:SS, duration: minute
        - start_time: 08:45:00
          duration: 280
        - start_time: 15:00:00
          duration: 820

quota:
    trade_quota: 1000000
    trade_tax_ratio: 0.0015
    trade_fee_ratio: 0.001425
    fee_discount: 0.28

target_cond:
    monitor_future_code: MXFI2
    real_time_rank: 20
    black_category:
        - 17
    black_stock:
        - 2317
        - 1314
        - 3481
        - 2412
        - 2002
        - 1102
    limit_volume: 1000
    price_limit:
        - low: 10
          high: 35

analyze:
    # unit: minute
    max_hold_time: 60

    # unit: %
    close_change_ratio_low: -2
    close_change_ratio_high: 2

    # unit: millisecond
    tick_analyze_period: 15000

    # unit: %
    volume_pr_limit: 95

    # unit: %
    all_out_in_ratio: 75
    all_in_out_ratio: 75

    # unit: times
    rsi_min_count: 150

    # unit: day
    ma_period: 60
