http:
    port: 26670

postgres:
    pool_max: 80

rabbitmq:
    wait_time: 5
    attempts: 10

sinopac:
    pool_max: 20

history:
    # unit: day
    history_close_period: 120
    history_tick_period: 14
    history_kbar_period: 120

trade_switch:
    simulation: true
    buy: true
    sell: true
    sell_first: true
    buy_later: true
    mean_time_forward: 5
    mean_time_reverse: 5
    forward_max: 30
    reverse_max: 30
    # unit: second
    hold_time_from_open: 45
    # unit: minute
    total_open_time: 270
    trade_in_end_time: 90
    trade_out_end_time: 150
    # unit: seccond
    trade_in_wait_time: 45
    trade_out_wait_time: 90
    cancel_wait_time: 20
    # open change ratio limit
    open_close_change_ratio_low: -2.5
    open_close_change_ratio_high: 2.5

quota:
    trade_quota: 1000000
    trade_tax_ratio: 0.0015
    trade_fee_ratio: 0.001425
    fee_discount: 0.35

target_cond:
    - limit_price_low: 10
      limit_price_high: 35
      limit_volume: 10000
      subscribe: true
    - limit_price_low: 35
      limit_price_high: 100
      limit_volume: 8000
      subscribe: false
    - limit_price_low: 100
      limit_price_high: 125
      limit_volume: 2000
      subscribe: true
    - limit_price_low: 125
      limit_price_high: 200
      limit_volume: 2000
      subscribe: false

analyze:
    # unit: %
    close_change_ratio_low: -1.5
    close_change_ratio_high: 1.5
    # unit: %
    out_in_ratio: 80
    in_out_ratio: 99
    # unit: %
    volume_pr_limit: 95
    # unit: millisecond
    tick_analyze_period: 7500
    # unit: times
    rsi_min_count: 600
    # rsi range: 0~1
    rsi_high: 50.2
    rsi_low: 49.8
    # unit: %
    max_loss: 2
    # unit: day
    ma_period: 60
