http:
    port: 26670

postgres:
    pool_max: 80

rabbitmq:
    wait_time: 5
    attempts: 10

sinopac:
    pool_max: 20

history:
    # unit: day
    history_close_period: 120
    history_tick_period: 10
    history_kbar_period: 120

trade_switch:
    simulation: false

    # unit: second
    hold_time_from_open: 45

    # unit: minute
    total_open_time: 270
    trade_in_end_time: 90
    trade_out_end_time: 150

    # unit: seccond
    trade_in_wait_time: 25
    trade_out_wait_time: 30
    cancel_wait_time: 15

    # open change ratio limit
    open_close_change_ratio_low: -2.5
    open_close_change_ratio_high: 2.5

quota:
    trade_quota: 1000000
    trade_tax_ratio: 0.0015
    trade_fee_ratio: 0.001425
    fee_discount: 0.28

target_cond:
    real_time_rank: 20
    black_stock:
        - 2317
        - 1314
        - 3481
        - 2412
    black_category:
        - 17
    price_volume_limit:
        - limit_price_low: 10
          limit_price_high: 35
          limit_volume: 10000
        - limit_price_low: 50
          limit_price_high: 75
          limit_volume: 5000
        - limit_price_low: 100
          limit_price_high: 125
          limit_volume: 2000

analyze:
    # unit: %
    close_change_ratio_low: -1.5
    close_change_ratio_high: 1.5

    # unit: %
    out_in_ratio: 95
    in_out_ratio: 95

    # unit: %
    volume_pr_limit: 98

    # unit: millisecond
    tick_analyze_period: 15000

    # unit: times
    rsi_min_count: 440

    # unit: day
    ma_period: 60
