simulation: false

trade_stock:
    allow_trade: false
    subscribe: true

    # unit: second
    hold_time_from_open: 45
    trade_in_wait_time: 45
    trade_out_wait_time: 60
    cancel_wait_time: 30

    # unit: minute
    total_open_time: 270
    trade_in_end_time: 90

trade_future:
    allow_trade: false
    subscribe: true
    quantity: 2

    # unit: dollar
    target_balance_high: 3
    target_balance_low: -3

    # unit: times
    trade_out_wait_times: 20

    # unit: seccond
    buy_sell_wait_time: 5
    tick_interval: 10

    # duration: minute
    trade_time_range:
        first_part_duration: 720
        second_part_duration: 285
    max_hold_time: 30

    # unit: volume/second
    rate_limit: 10

    # unit: %
    rate_change_ratio: 5
    out_in_ratio: 70
    in_out_ratio: 30

history:
    # unit: day
    history_close_period: 65
    history_tick_period: 12
    history_kbar_period: 65

    trigger_simulate: false

quota:
    stock_trade_quota: 1000000
    stock_fee_discount: 0.28
    future_trade_fee: 15

target_stock:
    real_time_rank: 20
    black_category:
        - 17
    black_stock:
        - 2317
        - 1314
        - 3481
        - 2412
        - 2002
        - 1102
    limit_volume: 1000
    price_limit:
        - low: 10
          high: 35

analyze_stock:
    # unit: minute
    max_hold_time: 60

    # unit: %
    close_change_ratio_low: -2
    close_change_ratio_high: 2
    volume_pr_limit: 95
    all_out_in_ratio: 75
    all_in_out_ratio: 75

    # unit: millisecond
    tick_analyze_period: 15000

    # unit: times
    rsi_min_count: 150

    # unit: day
    ma_period: 60
