Simulation: false
ManualTrade: true

TradeStock:
    AllowTrade: false

    # unit: second
    HoldTimeFromOpen: 45
    TradeInWaitTime: 45
    TradeOutWaitTime: 60
    CancelWaitTime: 30

    # unit: minute
    TotalOpenTime: 0
    TradeInEndTime: 0

TradeFuture:
    AllowTrade: false
    Quantity: 2

    # unit: dollar
    TargetBalanceHigh: 5
    TargetBalanceLow: -5

    # unit: times
    TradeOutWaitTimes: 20

    # unit: seccond
    BuySellWaitTime: 5
    TickInterval: 8

    # duration: minute
    TradeTimeRange:
        FirstPartDuration: 720
        SecondPartDuration: 285
    MaxHoldTime: 15

    # unit: volume/second
    RateLimit: 14

    # unit: %
    RateChangeRatio: 10
    OutInRatio: 55
    InOutRatio: 75

History:
    # unit: day
    HistoryClosePeriod: 60
    HistoryTickPeriod: 10
    HistoryKbarPeriod: 60

Quota:
    StockTradeQuota: 1000000
    StockFeeDiscount: 0.28
    FutureTradeFee: 15

AnalyzeStock:
    # unit: minute
    MaxHoldTime: 60

    # unit: %
    CloseChangeRatioLow: -2
    CloseChangeRatioHigh: 2
    VolumePRLimit: 95
    AllOutInRatio: 75
    AllInOutRatio: 75

    # unit: millisecond
    TickAnalyzePeriod: 15000

    # unit: times
    RSIMinCount: 150

    # unit: day
    MAPeriod: 60
