definitions:
  entity.HistoryKbar:
    properties:
      close:
        type: number
      high:
        type: number
      id:
        type: integer
      kbar_time:
        type: string
      low:
        type: number
      open:
        type: number
      stock:
        $ref: '#/definitions/entity.Stock'
      stock_num:
        type: string
      volume:
        type: integer
    type: object
  entity.Order:
    properties:
      action:
        type: integer
      order_id:
        type: string
      order_time:
        type: string
      price:
        type: number
      quantity:
        type: integer
      status:
        type: integer
      stock:
        $ref: '#/definitions/entity.Stock'
      stock_num:
        type: string
      trade_time:
        type: string
    type: object
  entity.Stock:
    properties:
      category:
        type: string
      day_trade:
        type: boolean
      exchange:
        type: string
      last_close:
        type: number
      name:
        type: string
      number:
        type: string
    type: object
  entity.Target:
    properties:
      id:
        type: integer
      rank:
        type: integer
      real_time_add:
        type: boolean
      stock:
        $ref: '#/definitions/entity.Stock'
      stock_num:
        type: string
      subscribe:
        type: boolean
      trade_day:
        type: string
      volume:
        type: integer
    type: object
  entity.TradeBalance:
    properties:
      discount:
        type: integer
      forward:
        type: integer
      id:
        type: integer
      original_balance:
        type: integer
      reverse:
        type: integer
      total:
        type: integer
      trade_count:
        type: integer
      trade_day:
        type: string
    type: object
  v1.BelowQuaterMA:
    properties:
      date:
        type: string
      stocks:
        items:
          $ref: '#/definitions/entity.Stock'
        type: array
    type: object
  v1.response:
    properties:
      error:
        example: message
        type: string
    type: object
  v1.stockDetailResponse:
    properties:
      stock_detail:
        items:
          $ref: '#/definitions/entity.Stock'
        type: array
    type: object
info:
  contact: {}
  description: Auto Trade
  title: TOC MACHINE TRADING
  version: 0.0.1
paths:
  /analyze/below-quater:
    get:
      consumes:
      - application/json
      description: getQuaterTargets
      operationId: getQuaterTargets
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/v1.BelowQuaterMA'
            type: array
      summary: getQuaterTargets
      tags:
      - analyze
  /basic/stock/repo:
    get:
      consumes:
      - application/json
      description: getAllRepoStock
      operationId: getAllRepoStock
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.stockDetailResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: getAllRepoStock
      tags:
      - basic
  /basic/stock/sinopac-to-repo:
    get:
      consumes:
      - application/json
      description: getAllSinopacStockAndUpdateRepo
      operationId: getAllSinopacStockAndUpdateRepo
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.stockDetailResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: getAllSinopacStockAndUpdateRepo
      tags:
      - basic
  /basic/system/terminate:
    put:
      consumes:
      - application/json
      description: terminateSinopac
      operationId: terminateSinopac
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: terminateSinopac
      tags:
      - system
  /history/day_kbar/{stock}/{start_date}/{interval}:
    get:
      consumes:
      - application/json
      description: getKbarData
      operationId: getKbarData
      parameters:
      - description: stock
        in: path
        name: stock
        required: true
        type: string
      - description: start_date
        in: path
        name: start_date
        required: true
        type: string
      - description: interval
        in: path
        name: interval
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.HistoryKbar'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: getKbarData
      tags:
      - history
  /order/all:
    get:
      consumes:
      - application/json
      description: getAllOrder
      operationId: getAllOrder
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Order'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: getAllOrder
      tags:
      - order
  /order/balance:
    get:
      consumes:
      - application/json
      description: getAllTradeBalance
      operationId: getAllTradeBalance
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.TradeBalance'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: getAllTradeBalance
      tags:
      - order
  /stream/tse/snapshot:
    get:
      consumes:
      - application/json
      description: getTSESnapshot
      operationId: getTSESnapshot
      produces:
      - application/json
      responses: {}
      summary: getTSESnapshot
      tags:
      - stream
  /targets:
    get:
      consumes:
      - application/json
      description: getTargets
      operationId: getTargets
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Target'
            type: array
      summary: getTargets
      tags:
      - target
swagger: "2.0"
