name: Workflow
run-name: ${{ github.actor }} is running TOC MACHINE TRADING actions 🍀

on:
    workflow_dispatch:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    REGISTRY: ghcr.io

jobs:
    Lint:
        runs-on: ubuntu-latest
        steps:
            - name: setup golang
              uses: actions/setup-go@v3
              with:
                  go-version: "1.20"

            - name: checkout
              uses: actions/checkout@v3

            - name: golangci-lint
              uses: golangci/golangci-lint-action@v3
              with:
                  version: v1.51.0

    Test:
        needs: Lint
        runs-on: ubuntu-latest
        steps:
            - name: setup golang
              uses: actions/setup-go@v3
              with:
                  go-version: "1.20"

            - name: checkout
              uses: actions/checkout@v3

            - name: build test
              run: go build -v ./...

            - name: go test
              run: cp ./configs/default.config.yml ./configs/config.yml

    Build:
        needs: Test
        env:
            REPOSITORY: "${{ github.repository }}"
            SHA: ${{ github.sha }}

        runs-on: ubuntu-latest
        steps:
            - name: set local env
              run: |
                  echo "REPOSITORY_LC=${REPOSITORY,,}" >> ${GITHUB_ENV}
                  echo "SHORT_SHA=$(echo ${SHA} | cut -c1-7)" >> ${GITHUB_ENV}

            - name: checkout
              uses: actions/checkout@v3

            - name: log in to the Container registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: build and push
              uses: docker/build-push-action@v3
              with:
                  push: true
                  tags: |
                      ${{ env.REGISTRY }}/${{ env.REPOSITORY_LC }}:${{ env.SHORT_SHA }}
                      ${{ env.REGISTRY }}/${{ env.REPOSITORY_LC }}:latest

    Trigger-Deployment:
        needs: Build
        runs-on: ubuntu-latest
        steps:
            - name: Trigger
              run: |
                  curl -X POST \
                      -H "Accept: application/vnd.github+json" \
                      -H "Authorization: Bearer ${{ secrets.ACTIONS_KEY }}"\
                      https://api.github.com/repos/ToC-Taiwan/ansible-machine/actions/workflows/actions.yml/dispatches \
                      -d '{"ref":"main","inputs":{"action":"setup_trader"}}'
            - uses: actions/checkout@v3
