name: Workflow
run-name: ${{ github.actor }} is running TOC MACHINE TRADING Actions 🚀

concurrency:
    group: production
    cancel-in-progress: true

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    Lint:
        runs-on: ubuntu-latest
        steps:
            - name: Setup GO
              uses: actions/setup-go@v3
              with:
                  go-version: 1.19.3

            - name: Checkout
              uses: actions/checkout@v3

            - name: golangci-lint
              uses: golangci/golangci-lint-action@v3
              with:
                  version: v1.50.1

    Test:
        needs: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Setup GO
              uses: actions/setup-go@v3
              with:
                  go-version: 1.19.3

            - name: Checkout
              uses: actions/checkout@v3

            - name: Build
              run: go build -v ./...

            - name: Test
              run: go test -v ./...

    Build:
        needs: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set outputs
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  push: true
                  tags: |
                      ${{ secrets.DOCKERHUB_USERNAME }}/toc-machine-trading:${{ steps.vars.outputs.sha_short }}
                      ${{ secrets.DOCKERHUB_USERNAME }}/toc-machine-trading:latest

    Deployment:
        needs: Build
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: deploying
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.TRADER_HOST }}
                  port: ${{ secrets.TRADER_PORT }}
                  username: ${{ secrets.TRADER_USERNAME }}
                  key: ${{ secrets.TRADER_KEY }}
                  script: |
                      docker kill toc-machine-trading || true
                      docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/toc-machine-trading:latest || true
                      docker system prune --volumes -f

                      rm -rf ~/toc-machine-trading-env && mkdir -p ~/toc-machine-trading-env && touch ~/toc-machine-trading-env/.env
                      rm -rf ~/toc-machine-trading-configs && mkdir -p ~/toc-machine-trading-configs && touch ~/toc-machine-trading-configs/config.yml
                      rm -rf ~/toc-machine-trading-logs
                      echo "${{ secrets.MACHINE_TRADING_ENV }}" > ~/toc-machine-trading-env/.env
                      echo "${{ secrets.MACHINE_TRADING_CONFIG }}" > ~/toc-machine-trading-configs/config.yml

                      docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
                      docker pull ${{ secrets.DOCKERHUB_USERNAME }}/toc-machine-trading:latest
                      docker run \
                        --name toc-machine-trading \
                        --network tocvlan \
                        --ip=172.20.10.228 \
                        --restart always \
                        -e TZ="Asia/Taipei" \
                        -v ~/toc-machine-trading-logs:/toc-machine-trading/logs \
                        -v ~/toc-machine-trading-env/.env:/toc-machine-trading/.env \
                        -v ~/toc-machine-trading-configs/config.yml:/toc-machine-trading/configs/config.yml \
                        -dt ${{ secrets.DOCKERHUB_USERNAME }}/toc-machine-trading:latest
